# locations.py
indian_states_districts = {
    "Andhra Pradesh": ["Anantapur", "Chittoor", "East Godavari", "Guntur", "Kadapa", "Krishna",
                        "Kurnool", "Nellore", "Prakasam", "Srikakulam", "Visakhapatnam", "Vizianagaram",
                        "West Godavari","Alluri Sitharama Raju", "Anakapalli", "Annamayya", "Bapatla",
                        "Eluru","Kakinada","Konaseema","Nandyal","NTR","Palnadu",
                        "Parvathipuram Manyam", "Sri Sathya Sai", "Tirupati"],
    "Arunachal Pradesh": ["Anjaw", "Changlang", "Dibang Valley", "East Siang", "Kamle", "Lohit",
                           "Longding", "Lower Dibang Valley", "Namsai", "Pakke-Kessang", "Siang",
                           "Tirap", "Upper Siang","East Kameng","Kra Daadi","Kurung Kumey","Lepa Rada",
                           "Lower Siang","Lower Subansiri","Papum Pare", "Shi Yomi","Tawang","Upper Subansiri",
                           "West Kameng","West Siang"],
    "Assam": ["Cachar", "Hailakandi", "Karimganj", "Dima Hasao", "East Karbi Anglong",
              "Morigaon", "Nagaon", "West Karbi Anglong","Baksa","Barpeta", "Bongaigaon",
              "Chirang", "Dhubri", "Goalpara", "Kamrup Rural","Kamrup Metropolitan","Kokrajhar",
              "Nalbari", "South Salmara-Mankachar","Darrang","Sonitpur", "Udalguri",
              "Charaideo","Dhemaji", "Dibrugarh", "Golaghat", "Jorhat", "Lakhimpur", "Majuli","Sivasagar","Tinsukia"],
    "Bihar": ["Bhagalpur", "Banka", "Darbhanga", "Madhubani", "Samastipur", "Madhepura",
              "Saharsa", "Supaul", "Arwal", "Aurangabad", "Gaya", "Jehanabad", "Nawada",
              "Begusarai", "Jamui", "Lakhisarai", "Munger", "Khagaria", "Sheikhpura", "Bhojpur",
              "Buxar", "Kaimur", "Nalanda", "Patna", "Rohtas", "Araria", "Katihar","Kishanganj",
              "Purnia", "Gopalganj", "Saran", "Siwan","East Champaran","Muzaffarpur","Sheohar",
              "Sitamarhi","Vaishali", "West Champaran"],
    "Chhattisgarh": ["Bastar", "Bijapur", "Dantewada", "Kanker", "Kondagaon", "Narayanpur",
                     "Sukma", "Bilaspur", "Gaurella-Pendra-Marwahi", "Janjgir-Champa", "Korba",
                     "Mungeli", "Raigarh", "Sarangarh-Bilaigarh", "Shakti", "Balod", "Bemetara",
                     "Durg", "Kabirdham", "Khairagarh-Chhuikhadan-Gandai", "Mohla-Manpur-Chowki",
                     "Rajnandgaon", "Baloda Bazar", "Dhamtari", "Gariaband", "Mahasamund", "Raipur",
                     "Balrampur-Ramanujganj", "Jashpur", "Koriya", "Manendragarh", "Surajpur", "Surguja"],
    "Goa": ["North Goa", "South Goa"],
    "Gujarat": ["Ahmedabad", "Amreli", "Anand", "Aravalli", "Banaskantha", "Bharuch", "Bhavnagar",
                "Botad", "Chhota Udaipur", "Dahod", "Dang", "Devbhoomi Dwarka", "Gandhinagar",
                "Gir Somnath", "Jamnagar", "Junagadh", "Kheda", "Kutch", "Mahisagar", "Mehsana",
                "Morbi", "Narmada", "Navsari", "Panchmahal", "Patan", "Porbandar", "Rajkot",
                "Sabarkantha", "Surat", "Surendranagar", "Tapi", "Vadodara","Valsad"],
    "Haryana": ["Ambala", "Kurukshetra", "Panchkula", "Yamuna Nagar", "Faridabad", "Nuh",
                "Palwal", "Gurugram", "Mahendragarh", "Rewari", "Fatehabad", "Hisar", "Jind",
                "Sirsa", "Kaithal", "Karnal", "Panipat", "Bhiwani", "Charkhi Dadri", "Jhajjar",
                "Rohtak", "Sonipat"],
    "Himachal Pradesh": ["Chamba", "Kangra", "Una", "Bilaspur", "Hamirpur", "Kullu",
                          "Lahaul and Spiti", "Mandi", "Kinnaur", "Shimla", "Sirmaur", "Solan"],
    "Jharkhand": ["East Singhbhum", "Seraikela Kharsawan", "West Singhbhum", "Chatra", "Bokaro",
                  "Dhanbad", "Giridih", "Hazaribag", "Koderma", "Ramgarh", "Garhwa", "Latehar",
                  "Palamu", "Deoghar", "Dumka", "Godda", "Jamtara", "Pakur", "Sahebganj", "Gumla",
                  "Lohardaga", "Khunti", "Ranchi", "Simdega"],
    "Karnataka": ["Bengaluru Rural", "Bangalore Urban", "Chikkaballapur", "Chitradurga", "Davanagere",
                  "Kolar", "Ramanagara", "Shivamogga", "Tumakuru", "Bagalkot", "Belagavi", "Dharwad",
                  "Gadag", "Haveri", "Uttara Kannada", "Vijayapura", "Ballari", "Bidar", "Kalaburagi",
                  "Koppal", "Raichur", "Yadgir", "Chamarajnagar", "Chikkamagaluru", "Dakshina Kannada",
                  "Hassan", "Kodagu", "Mandya", "Mysuru", "Udupi"],
    "Kerala": ["Alappuzha", "Ernakulam", "Idukki", "Kannur", "Kasaragod", "Kollam", "Kottayam",
               "Kozhikode", "Malappuram", "Palakkad", "Pathanamthitta", "Thiruvananthapuram",
               "Thrissur", "Wayanad"],
    "Madhya Pradesh": ["Bhopal", "Raisen", "Rajgarh", "Sehore", "Vidisha", "Bhind", "Morena",
                        "Sheopur", "Ashoknagar", "Datia", "Guna", "Gwalior", "Shivpuri", "Alirajpur",
                        "Barwani", "Burhanpur", "Dhar", "Indore", "Jhabua", "Khandwa", "Khargone",
                        "Balaghat", "Chhindwara", "Dindori", "Jabalpur", "Katni", "Mandla",
                        "Narsinghpur", "Seoni", "Betul", "Harda", "Hoshangabad", "Rewa", "Satna",
                        "Sidhi", "Singrauli", "Chhatarpur", "Damoh", "Niwari", "Panna", "Sagar",
                        "Tikamgarh", "Anuppur", "Shahdol", "Umaria", "Agar Malwa", "Dewas",
                        "Mandsaur", "Neemuch", "Ratlam", "Shajapur", "Ujjain"],
    "Maharashtra": ["Akola", "Amravati", "Buldana", "Washim", "Yavatmal", "Aurangabad", "Beed",
                        "Hingoli", "Jalna", "Latur", "Nanded", "Osmanabad", "Parbhani", "Mumbai City",
                        "Mumbai Suburban", "Palghar", "Raigad", "Ratnagiri", "Sindhudurg", "Thane",
                        "Bhandara", "Chandrapur", "Gadchiroli", "Gondia", "Nagpur", "Wardha", "Dhule",
                        "Jalgaon", "Nandurbar", "Nashik", "Ahmednagar", "Kolhapur", "Pune", "Sangli",
                        "Satara", "Solapur"],
    "Manipur": ["Bishnupur", "Chandel", "Churachandpur", "Imphal East", "Imphal West", "Jiribam",
                "Kakching", "Kamjong", "Kangpokpi", "Noney", "Pherzawl", "Senapati", "Tamenglong",
                "Tengnoupal", "Thoubal", "Ukhrul"],
    "Meghalaya": ["West Jaintia Hills", "East Jaintia Hills", "East Khasi Hills", "West Khasi Hills",
                  "South West Khasi Hills", "Ri-Bhoi", "East Garo Hills", "West Garo Hills",
                  "North Garo Hills", "South Garo Hills", "South West Garo Hills", "Eastern West Khasi Hills"],
    "Mizoram": ["Aizawl", "Champhai", "Hnahthial", "Khawzawl", "Kolasib", "Lawngtlai", "Lunglei",
                "Mamit", "Saiha", "Saitual", "Serchhip"],
    "Nagaland": ["Dimapur", "Kiphire", "Kohima", "Longleng", "Mokokchung", "Mon", "Noklak", "Peren",
                 "Phek", "Tuensang", "Wokha", "Zunheboto","Chümoukedima","Tseminyü","Niuland","Shamator"],
    "Odisha": ["Balasore", "Bhadrak", "Cuttack", "Jajpur", "Jagatsinghpur", "Kendrapara", "Khordha",
               "Mayurbhanj", "Nayagarh", "Puri", "Angul", "Balangir", "Bargarh", "Deogarh",
               "Dhenkanal", "Jharsuguda", "Kendujhar", "Sambalpur", "Subarnapur", "Sundargarh",
               "Boudh", "Gajapati", "Ganjam", "Kalahandi", "Kandhamal", "Koraput", "Malkangiri",
               "Nabarangpur", "Nuapada", "Rayagada"],
    "Punjab": ["Bathinda", "Faridkot", "Mansa", "Fazilka", "Ferozepur", "Moga", "Sri Muktsar Sahib",
               "Amritsar", "Gurdaspur", "Hoshiarpur", "Jalandhar", "Kapurthala", "Pathankot",
               "Tarn Taran", "Barnala", "Fatehgarh Sahib", "Ludhiana", "Patiala", "Sangrur",
               "Rupnagar", "Sahibzada Ajit Singh Nagar", "Shahid Bhagat Singh Nagar"],
    "Rajasthan": ["Ajmer", "Bhilwara", "Nagaur", "Tonk", "Bharatpur", "Dholpur", "Karauli",
                 "Sawai Madhopur", "Bikaner", "Churu", "Hanumangarh", "Sri Ganganagar", "Alwar",
                 "Dausa", "Jaipur", "Jhunjhunu", "Sikar", "Barmer", "Jaisalmer", "Jalore",
                 "Jodhpur", "Pali", "Sirohi", "Baran", "Bundi", "Jhalawar", "Kota", "Banswara",
                 "Chittorgarh", "Dungarpur", "Pratapgarh", "Rajsamand", "Udaipur"],
    "Sikkim": ["Gangtok", "Mangan", "Namchi", "Gyalshing", "Pakyong", "Soreng"],
    "Tamil Nadu": ["Ariyalur", "Chengalpattu", "Chennai", "Coimbatore", "Cuddalore", "Dharmapuri",
                  "Dindigul", "Erode", "Kallakurichi", "Kanchipuram", "Kanyakumari", "Karur",
                  "Krishnagiri", "Madurai", "Mayiladuthurai", "Nagapattinam", "Namakkal", "Nilgiris",
                  "Perambalur", "Pudukkottai", "Ramanathapuram", "Ranipet", "Salem", "Sivaganga",
                  "Tenkasi", "Thanjavur", "Theni", "Thoothukudi", "Tiruchirappalli", "Tirunelveli",
                  "Tirupattur", "Tirupur", "Tiruvallur", "Tiruvannamalai", "Tiruvarur", "Vellore",
                  "Viluppuram", "Virudhunagar"],
    "Telangana": ["Adilabad", "Bhadradri Kothagudem", "Hyderabad", "Jagtial", "Jangaon",
                   "Jayashankar Bhupalpally", "Jogulamba Gadwal", "Kamareddy", "Karimnagar", "Khammam",
                   "Komaram Bheem", "Mahabubabad", "Mahbubnagar", "Mancherial", "Medak",
                   "Medchal-Malkajgiri", "Mulugu", "Nagarkurnool", "Nalgonda", "Narayanpet", "Nirmal",
                   "Nizamabad", "Peddapalli", "Rajanna Sircilla", "Ranga Reddy", "Sangareddy",
                   "Siddipet", "Suryapet", "Vikarabad", "Wanaparthy", "Warangal Rural",
                   "Warangal Urban", "Yadadri Bhuvanagiri"],
    "Tripura": ["Dhalai", "Gomati", "Khowai", "North Tripura", "Sepahijala", "South Tripura",
             "Unakoti", "West Tripura"],
    "Uttarakhand": ["Chamoli", "Dehradun", "Haridwar", "Pauri Garhwal", "Rudraprayag",
                     "Tehri Garhwal", "Uttarkashi", "Almora", "Bageshwar", "Champawat", "Nainital",
                     "Pithoragarh", "Udham Singh Nagar"],
    "Uttar Pradesh": ["Agra", "Firozabad", "Mainpuri", "Mathura", "Aligarh", "Etah", "Hathras",
                       "Kasganj", "Ambedkar Nagar", "Amethi", "Ayodhya", "Barabanki", "Sultanpur",
                       "Azamgarh", "Ballia", "Mau", "Badaun", "Bareilly", "Pilibhit", "Shahjahanpur",
                       "Basti", "Sant Kabir Nagar", "Siddharthnagar", "Banda", "Chitrakoot", "Hamirpur",
                       "Mahoba", "Bahraich", "Balarampur", "Gonda", "Shravasti", "Deoria", "Gorakhpur",
                       "Kushinagar", "Maharajganj", "Jalaun", "Jhansi", "Lalitpur", "Auraiya", "Etawah",
                       "Farrukhabad", "Kannauj", "Kanpur Dehat", "Kanpur Nagar", "Hardoi",
                       "Lakhimpur Kheri", "Lucknow", "Raebareli", "Sitapur", "Unnao", "Baghpat",
                       "Bulandshahar", "Gautam Buddha Nagar", "Ghaziabad", "Hapur", "Meerut",
                       "Bhadohi", "Mirzapur", "Sonbhadra", "Amroha", "Bijnor", "Moradabad", "Rampur",
                       "Sambhal", "Fatehpur", "Kaushambi", "Pratapgarh", "Prayagraj", "Muzaffarnagar",
                       "Saharanpur", "Shamli", "Chandauli", "Ghazipur", "Jaunpur", "Varanasi"],
    "West Bengal": ["Birbhum", "Hooghly", "Paschim Bardhaman", "Purba Bardhaman", "Alipurduar",
                     "Cooch Behar", "Darjeeling", "Jalpaiguri", "Kalimpong", "Dakshin Dinajpur",
                     "Malda", "Murshidabad", "Uttar Dinajpur", "Bankura", "Jhargram",
                     "Paschim Medinipur", "Purba Medinipur", "Purulia", "Howrah", "Kolkata", "Nadia",
                     "North 24 Parganas", "South 24 Parganas"]
}