"""Add registration_number to Car model

Revision ID: cf5d6c3f9f89
Revises: b76f06d2bc88
Create Date: 2025-02-18 20:26:02.680571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf5d6c3f9f89'
down_revision = 'b76f06d2bc88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.add_column(sa.Column('registration_number', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.drop_column('registration_number')

    # ### end Alembic commands ###
